Repository opexdev/mobile-app, pull requests merged in 2023-08, with the labels that each got.

#24 Add multi network for deposit address
  public/assets/locales/en/translation.json
  public/assets/locales/fa/translation.json
  src/components/TextInput/TextInput.js
  src/main/Mobile/Pages/UserPanel/Secttions/Content/components/Wallet/components/Deposit/Deposit.js
  src/main/Mobile/Pages/UserPanel/Secttions/Content/components/Wallet/components/Deposit/Deposit.module.css
  src/main/Mobile/Pages/UserPanel/Secttions/Content/components/Wallet/components/Deposit/components/Address/Address.js
  src/queries/hooks/useGetDepositAddress.js
  yarn.lock
Labels: enhancement

#25 Release v1.0.0-beta.3
  package.json
  public/assets/locales/en/translation.json
  public/assets/locales/fa/translation.json
  public/index.html
  src/assets/images.js
  src/assets/images/src/testTron.svg
  src/assets/images/src/tron.svg
  src/components/TextInput/TextInput.js
  src/index.js
  src/main/Mobile/Pages/Login/components/ForgetPassword/ForgetPassword.js
  src/main/Mobile/Pages/Login/components/RegisterForm/RegisterForm.js
  src/main/Mobile/Pages/UserPanel/Secttions/Content/components/Wallet/components/Deposit/Deposit.js
  src/main/Mobile/Pages/UserPanel/Secttions/Content/components/Wallet/components/Deposit/Deposit.module.css
  src/main/Mobile/Pages/UserPanel/Secttions/Content/components/Wallet/components/Deposit/components/Address/Address.js
  src/queries/hooks/useGetDepositAddress.js
  yarn.lock
Labels: bug, enhancement

#26 Release v1.0.0-beta.3
  package.json
Labels: bug, enhancement

#28 Update to React 18
  .yarn/releases/yarn-3.2.3.cjs
  .yarnrc.yml
  package.json
  public/assets/locales/en/translation.json
  public/assets/locales/fa/translation.json
  src/components/Footer/Footer.js
  src/components/Loading/Loading.js
  src/constants/chart.js
  src/index.js
  src/main/Browser/Browser.css
  src/main/Browser/Browser.js
  src/main/Mobile/Pages/Login/components/LoginForm/LoginForm.js
  src/main/Mobile/Pages/UserPanel/Secttions/Content/Content.js
  src/main/Mobile/Pages/UserPanel/Secttions/Content/components/Market/Sections/OrderBookSection/OrderBookSection.js
  src/main/Mobile/Pages/UserPanel/Secttions/Content/components/Market/components/LastTrades/components/LastTradesTable/LastTradesTable.js
  src/main/Mobile/Pages/UserPanel/Secttions/Content/components/Market/components/Order/Order.js
  src/main/Mobile/Pages/UserPanel/Secttions/Content/components/Market/components/Order/components/BuyOrder/BuyOrder.js
  src/main/Mobile/Pages/UserPanel/Secttions/Content/components/Market/components/Order/components/SellOrder/SellOrder.js
  src/main/Mobile/Pages/UserPanel/Secttions/Content/components/Market/components/OrderBook/OrderBook.js
  src/main/Mobile/Pages/UserPanel/Secttions/Content/components/Market/components/OrderBook/api/orderBook.js
  src/main/Mobile/Pages/UserPanel/Secttions/Content/components/Market/components/OrderBook/components/OrderBookTable/OrderBookTable.js
  src/main/Mobile/Pages/UserPanel/Secttions/Content/components/Market/components/OrderBook/components/OrderBookTable/OrderBookTable.module.css
  src/main/Mobile/Pages/UserPanel/Secttions/Content/components/Market/components/OrderBook/components/OrderBookTableSafari/OrderBookTableSafari.js
  src/main/Mobile/Pages/UserPanel/Secttions/Content/components/Market/components/OrderBook/components/OrderBookTableSafari/OrderBookTableSafari.module.css
  src/main/Mobile/Pages/UserPanel/Secttions/Content/components/Market/components/Overview/Overview.js
  src/main/Mobile/Pages/UserPanel/Secttions/Content/components/Market/components/Overview/api/overview.js
  src/main/Mobile/Pages/UserPanel/Secttions/Content/components/Market/components/Overview/components/InformationBlock/InformationBlock.js
  src/main/Mobile/Pages/UserPanel/Secttions/Content/components/Market/components/TradingView/TradingView.js
  src/main/Mobile/Pages/UserPanel/Secttions/Content/components/Market/components/TradingView/components/MarketChart/MarketChart.js
  src/main/Mobile/Pages/UserPanel/Secttions/Content/components/Settings/Settings.js
  src/main/Mobile/Pages/UserPanel/Secttions/Content/components/Wallet/Wallet.js
  src/main/Mobile/Pages/UserPanel/Secttions/Content/components/Wallet/components/Deposit/Deposit.js
  src/main/Mobile/Pages/UserPanel/Secttions/Header/Header.js
  src/main/Mobile/Pages/UserPanel/Secttions/Header/components/WalletHeader/WalletHeader.js
  src/main/Mobile/Pages/UserPanel/Secttions/Menu/Menu.js
  src/main/Mobile/Pages/UserPanel/Secttions/SubHeader/components/MarketSubHeader/MarketSubHeader.js
  src/main/main.js
  yarn.lock
Labels: enhancement

#29 Refactor login with js-api-client
  src/components/SideMenu/SideMenu.js
  src/main/Mobile/Pages/Login/Login.js
  src/main/Mobile/Pages/Login/Login.module.css
  src/main/Mobile/Pages/Login/api/auth.js
  src/main/Mobile/Pages/Login/components/EmailVerification/EmailVerification.js
  src/main/Mobile/Pages/Login/components/ForgetPassword/ForgetPassword.js
  src/main/Mobile/Pages/Login/components/LoginForm/LoginForm.js
  src/main/Mobile/Pages/Login/components/LoginLoading/LoginFormLoading.js
  src/main/Mobile/Pages/Login/components/OTPForm/OTPForm.js
  src/main/Mobile/Pages/Login/components/RegisterForm/RegisterForm.js
Labels: bug, enhancement

#34 Release v1.0.1-beta.4
  package.json
  public/assets/locales/en/translation.json
  src/index.css
  src/main/Mobile/Pages/Login/Login.js
  src/main/Mobile/Pages/Login/components/RegisterForm/RegisterForm.js
  src/main/Mobile/Pages/User/components/ForgetPassword/ForgetPassword.js
  src/main/Mobile/Pages/UserPanel/Secttions/Content/components/Settings/components/Security/components/ChangePassword/ChangePassword.js
  src/main/Mobile/Styles/Mobille.css
Labels: bug

#36 Fix transaction hash in deposit
  src/main/Mobile/Pages/UserPanel/Secttions/Content/components/Wallet/components/Transaction/components/DepositWithdrawTx/components/DepositWithdrawTxTables/DepositWithdrawTxTables.js
Labels: bug
